sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION package doc
  - sbt scalafmtTest
  - sbt ++2.11.11 readme/run
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.4
  - 2.13.0-M2
jdk:
  - oraclejdk8
env:
  - SCALAJS_VERSION=0.6.22
  - SCALAJS_VERSION=1.0.0-M3
matrix:
  exclude:
    - scala: 2.10.7
      env: SCALAJS_VERSION=1.0.0-M3

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
