dist: xenial
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION package doc example/compile
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.10
  - 2.13.5
  - 3.0.0-RC1
jdk:
  - openjdk8
env:
  - SCALAJS_VERSION=0.6.28
  - SCALAJS_VERSION=1.5.0
matrix:
  exclude:
    - scala: 2.10.7
      env: SCALAJS_VERSION=1.5.0
  include:
    - scala: 2.12.10
      env: SCALAJS_VERSION=1.5.0
      script:
        - sbt readme/run

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
