sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION package doc example/compile
  - sbt scalafmtCheck
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC1
jdk:
  - oraclejdk8
env:
  - SCALAJS_VERSION=0.6.27
  - SCALAJS_VERSION=1.0.0-M7
matrix:
  exclude:
    - scala: 2.10.7
      env: SCALAJS_VERSION=1.0.0-M7
  include:
    - scala: 2.12.8
      env: SCALAJS_VERSION=0.6.27
      script:
        - sbt readme/run

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
