name: CI

on:
  pull_request:
  push:
    tags-ignore:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.11.12", "2.12.15", "2.13.6", "3.1.3"]
    steps:

      - uses: actions/checkout@v3

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1

      - name: Build and test
        run: sbt -DCI=1 "++${{ matrix.scalaversion }}" test package doc

      - name: Validate formatting
        run: sbt -DCI=1 "++${{ matrix.scalaversion }}" dom/scalafmtCheck

      - name: Validate api report
        if: matrix.scalaversion != '2.11.12' && matrix.scalaversion != '3.1.3'
        run: ./api-reports/validate "${{ matrix.scalaversion }}"

  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: japgolly/setup-everything-scala@v3.1
      - name: Readme generation
        run: sbt readme/run
